/*PassengerDetails


Indian Railways is a state owned national transporter, responsible for rail transport in India. It is owned and operated by the Government of India through the Ministry of Railways. Railway ticket generation  happens using dot matrix printer. For example, the reservation chart that is stuck outside the train, has multiple copies. One copy goes to the head office, one to the ticket checker, one on the platform and one the train. The multiple copies are printed simultaneously and with the help of  the dot matrix printer.

Create an application which is used to print the passengers details 

Consider a class Passenger with the following private variables:

int ticketid
String name
String gender
String address
Initialize the values using constructor and display the details as generated by dot matrix printer.

[Hint : override the "public String toString()" method]

Write a class Main to get the input from the user as shown in the sample below and print the details of the passenger by using the overridden toString method.

Sample Input 1:

Enter the no.of passengers:

2

Passenger 1

Enter the ticketid:
100
Enter the name:
Sudha

Enter the gender:

Female

Enter the address:
Coimbatore

Passenger 2

Enter the ticketid:
101
Enter the name:
Bavi

Enter the gender:

Female

Enter the address:
Bangalore

Sample Output 1:

ticketid:100,name:Sudha,gender:Female,address:Coimbatore
ticketid:101,name:Bavi,gender:Female,address:Bangalore*/

//Passenger.java

public class Passenger{
private int ticketid;
private String name;
private String gender;
private String address;
public Passenger(int ticketid,String name,String gender,String address){
this.ticketid=ticketid;
this.name=name;
this.gender=gender;
this.address=address;
}
public void setTicketid(int ticketid){
this.ticketid=ticketid;
}
public void setName(String name){
this.name=name;
}
public void setGender(String gender){
this.gender=gender;
}
public void setAddress(String address){
this.address=address;
}
public int getTicketid(){
return ticketid;
}
public String getName(){
return name;
}
public String getGender(){
return gender;
}
public String getAddress(){
return address;
}
public String toString(){
String str="ticketid:"+getTicketid()+",name:"+getName()+",gender:"+getGender()+",address:"+getAddress();
return str;
}
}

//Main.java

import java.util.Scanner;
public class Main{
public static void main (String[] args) {
Scanner s=new Scanner(System.in);
System.out.println("Enter the no.of passengers:");
int num=s.nextInt();
Passenger[] p=new Passenger[num];
for (int i=1;i<=num;i++) {
System.out.println("Passenge "+i);
System.out.println("Enter the ticketid:");
int id=s.nextInt();
System.out.println("Enter the name:");
String name=s.next();
name+=s.nextLine();
System.out.println("Enter the gender:");
String gender=s.next();
gender+=s.nextLine();
System.out.println("Enter the address:");
String address=s.next();
address+=s.nextLine();
p[i-1]=new Passenger(id,name,gender,address);
}
for(int i=0;i<num;i++){
String str=p[i].toString();
System.out.println(str);
}
}
}

